[build]
  command = "CI= npm run build"
  publish = "build"

[build.environment]
  # Disable secrets scanning for expected React env vars
  SECRETS_SCAN_ENABLED = "false"

# Or alternatively, omit specific keys:
# [secrets]
#   omit_keys = [
#     "REACT_APP_TICKETMASTER_APIKEY",
#     "REACT_APP_FIREBASE_API_KEY",
#     "REACT_APP_FIREBASE_AUTH_DOMAIN",
#     "REACT_APP_FIREBASE_PROJECT_ID",
#     "REACT_APP_FIREBASE_STORAGE_BUCKET",
#     "REACT_APP_FIREBASE_MESSAGING_SENDER_ID",
#     "REACT_APP_FIREBASE_APP_ID",
#     "REACT_APP_FIREBASE_MEASUREMENT_ID"
#   ]
